name: my-environment
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - flake8
  - pytest

- name: Install dependencies
  run: |
    conda env update --file .github/workflows/python-package-conda.yml --name base
