name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Conda environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml  # Update this path if necessary
        python-version: 3.8

    - name: Install dependencies
      run: conda env update --file environment.yml --name base

    - name: Run tests
      run: |
        source activate base
        python -m unittest discover
